[package]
name = "websocket_chat_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
sha1 = "0.10.6"
base64 = { version = "0.21.5", features = [] }